-- Additional schema for ARON Project Management Configurations

CREATE TABLE IF NOT EXISTS system_settings (
    setting_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_name VARCHAR(250) NOT NULL DEFAULT 'ARON Project Management',
    logo_url TEXT,
    banner_url TEXT,
    smtp_host VARCHAR(250),
    smtp_port INT DEFAULT 587,
    smtp_username VARCHAR(250),
    smtp_password VARCHAR(250),
    smtp_enable_ssl BOOLEAN DEFAULT TRUE,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Seed initial settings
INSERT INTO system_settings (app_name, logo_url, banner_url, smtp_host, smtp_port, smtp_username, smtp_password, smtp_enable_ssl)
VALUES (
    'ARON Project Management',
    'https://raw.githubusercontent.com/vitejs/vite/main/packages/vite/src/node/logo.png', -- Default logo
    'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1600', -- Technology banner
    'smtp.gmail.com',
    587,
    'noreply.aron.erp@gmail.com',
    'sampleapppassword123',
    TRUE
) ON CONFLICT DO NOTHING;

-- Alter tables to support long Base64 strings for local image upload
ALTER TABLE system_settings ALTER COLUMN logo_url TYPE TEXT;
ALTER TABLE system_settings ALTER COLUMN banner_url TYPE TEXT;
ALTER TABLE projects ALTER COLUMN logo_path TYPE TEXT;
ALTER TABLE users ALTER COLUMN avatar_path TYPE TEXT;

-- Add account expiry date field to users
ALTER TABLE users ADD COLUMN IF NOT EXISTS expirydate TIMESTAMP WITH TIME ZONE;

-- Add Sharepoint/OneDrive folder link to projects
ALTER TABLE projects ADD COLUMN IF NOT EXISTS sharepointfolderlink TEXT;
