-- Additional schema for ARON Project Management Configurations

CREATE TABLE IF NOT EXISTS system_settings (
    setting_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_name VARCHAR(250) NOT NULL DEFAULT 'ARON Project Management',
    logo_url VARCHAR(500),
    banner_url VARCHAR(500),
    smtp_host VARCHAR(250),
    smtp_port INT DEFAULT 587,
    smtp_username VARCHAR(250),
    smtp_password VARCHAR(250),
    smtp_enable_ssl BOOLEAN DEFAULT TRUE,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Seed initial settings
INSERT INTO system_settings (app_name, logo_url, banner_url, smtp_host, smtp_port, smtp_username, smtp_password, smtp_enable_ssl)
VALUES (
    'ARON Project Management',
    'https://raw.githubusercontent.com/vitejs/vite/main/packages/vite/src/node/logo.png', -- Default logo
    'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1600', -- Technology banner
    'smtp.gmail.com',
    587,
    'noreply.aron.erp@gmail.com',
    'sampleapppassword123',
    TRUE
) ON CONFLICT DO NOTHING;
