-- ============================================================================
-- DATABASE SCHEMA DESIGN FOR ARON ERP PROJECT MANAGEMENT SYSTEM (ARON ERP-PM)
-- Target RDBMS: PostgreSQL 12+
-- ============================================================================

-- ============================================================================
-- 1. BASE TABLES: PROJECTS, SITES, & TEAMS
-- ============================================================================

CREATE TABLE Projects (
    ProjectId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProjectCode VARCHAR(50) NOT NULL UNIQUE,
    ProjectName VARCHAR(250) NOT NULL,
    Address VARCHAR(500) NULL,
    SitesCount INT NOT NULL DEFAULT 1,
    ContactInfo VARCHAR(500) NULL,
    LogoPath VARCHAR(500) NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedDate TIMESTAMPTZ NULL
);

CREATE TABLE ProjectSites (
    SiteId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProjectId INT NOT NULL REFERENCES Projects(ProjectId) ON DELETE CASCADE,
    SiteName VARCHAR(250) NOT NULL,
    Address VARCHAR(500) NULL,
    ContactName VARCHAR(100) NULL,
    Phone VARCHAR(50) NULL,
    Email VARCHAR(150) NULL,
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Organization teams (ARON, Client, Partner)
CREATE TABLE Teams (
    TeamId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProjectId INT NOT NULL REFERENCES Projects(ProjectId) ON DELETE CASCADE,
    TeamName VARCHAR(150) NOT NULL, -- e.g., ARON Team, Client Team, Partner Team
    ParentTeamId INT NULL REFERENCES Teams(TeamId) ON DELETE RESTRICT,
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Functional Sub-teams (PO-INV, AP, FIN, Tech, DBA...)
CREATE TABLE FunctionalTeams (
    FunctionalTeamId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TeamId INT NOT NULL REFERENCES Teams(TeamId) ON DELETE CASCADE,
    FunctionalTeamName VARCHAR(150) NOT NULL, -- e.g., Team PO-INV, Team AP, Team Tech...
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 2. USERS, ROLES, & PROJECT MEMBERSHIP (RBAC & MATRIX ALLOCATION)
-- ============================================================================

-- Master Roles
CREATE TABLE Roles (
    RoleId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RoleCode VARCHAR(50) NOT NULL UNIQUE, -- SYSTEM_ADMIN, DIRECTOR, PM, LEADER, MEMBER
    RoleName VARCHAR(100) NOT NULL,
    HierarchyLevel INT NOT NULL -- 1: Admin, 2: Director, 3: PM, 4: Leader, 5: Member
);

CREATE TABLE Users (
    UserId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    FullName VARCHAR(150) NOT NULL,
    Title VARCHAR(100) NULL,
    Email VARCHAR(150) NOT NULL UNIQUE,
    Phone VARCHAR(50) NULL,
    AvatarPath VARCHAR(500) NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    ResetToken VARCHAR(255) NULL,
    ResetTokenExpiry TIMESTAMPTZ NULL,
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedDate TIMESTAMPTZ NULL
);

-- Project Members table map Users to Projects with specific Roles and Functional Teams
CREATE TABLE ProjectMembers (
    ProjectMemberId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProjectId INT NOT NULL REFERENCES Projects(ProjectId) ON DELETE CASCADE,
    UserId INT NOT NULL REFERENCES Users(UserId) ON DELETE CASCADE,
    FunctionalTeamId INT NULL REFERENCES FunctionalTeams(FunctionalTeamId) ON DELETE SET NULL,
    RoleId INT NOT NULL REFERENCES Roles(RoleId) ON DELETE RESTRICT,
    DailyRate DECIMAL(18,2) NULL, -- Costing (PM and above only)
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_Project_User UNIQUE(ProjectId, UserId)
);

-- ============================================================================
-- 3. TASKS & GANTT CHART (3 levels, parent-child links)
-- ============================================================================

CREATE TABLE Tasks (
    TaskId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProjectId INT NOT NULL REFERENCES Projects(ProjectId) ON DELETE CASCADE,
    TaskCode VARCHAR(50) NOT NULL, -- e.g., 1.1, 1.1.2 (WBS Code)
    TaskName VARCHAR(250) NOT NULL,
    Description TEXT NULL,
    TaskLevel INT NOT NULL CHECK (TaskLevel IN (1, 2, 3)), -- level 1, 2, 3
    ParentTaskId INT NULL REFERENCES Tasks(TaskId) ON DELETE RESTRICT,
    AssigneeMemberId INT NULL REFERENCES ProjectMembers(ProjectMemberId) ON DELETE SET NULL,
    ApproverMemberId INT NULL REFERENCES ProjectMembers(ProjectMemberId) ON DELETE SET NULL,
    StartDatePlanned DATE NOT NULL,
    EndDatePlanned DATE NOT NULL,
    StartDateActual DATE NULL,
    EndDateActual DATE NULL,
    DurationPlanned INT NOT NULL, -- in days
    ProgressPercent DECIMAL(5,2) NOT NULL DEFAULT 0.00, -- 0.00 to 100.00
    Status VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED', -- NOT_STARTED, IN_PROGRESS, PENDING_APPROVAL, COMPLETED, DELAYED
    IsVisibleToAll BOOLEAN NOT NULL DEFAULT TRUE, -- Custom visibility setting
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedDate TIMESTAMPTZ NULL,
    CONSTRAINT UQ_Project_TaskCode UNIQUE(ProjectId, TaskCode)
);

-- Gantt Dependencies (Predecessors / Successors)
CREATE TABLE TaskDependencies (
    DependencyId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PredecessorTaskId INT NOT NULL REFERENCES Tasks(TaskId) ON DELETE CASCADE,
    SuccessorTaskId INT NOT NULL REFERENCES Tasks(TaskId) ON DELETE CASCADE,
    DependencyType VARCHAR(10) NOT NULL DEFAULT 'FS', -- FS, SS, FF, SF
    LagDays INT NOT NULL DEFAULT 0,
    CONSTRAINT UQ_Task_Dependency UNIQUE(PredecessorTaskId, SuccessorTaskId)
);

-- ============================================================================
-- 4. ISSUES & TIMESHEETS
-- ============================================================================

CREATE TABLE Issues (
    IssueId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProjectId INT NOT NULL REFERENCES Projects(ProjectId) ON DELETE CASCADE,
    Title VARCHAR(250) NOT NULL,
    Description TEXT NOT NULL,
    Severity VARCHAR(20) NOT NULL CHECK (Severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    Status VARCHAR(20) NOT NULL DEFAULT 'OPEN', -- OPEN, IN_PROGRESS, RESOLVED, CLOSED
    RaisedByMemberId INT NOT NULL REFERENCES ProjectMembers(ProjectMemberId) ON DELETE RESTRICT,
    AssignedToMemberId INT NULL REFERENCES ProjectMembers(ProjectMemberId) ON DELETE SET NULL,
    TargetResolveDate DATE NULL,
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedDate TIMESTAMPTZ NULL
);

CREATE TABLE Timesheets (
    TimesheetId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProjectId INT NOT NULL REFERENCES Projects(ProjectId) ON DELETE CASCADE,
    MemberId INT NOT NULL REFERENCES ProjectMembers(ProjectMemberId) ON DELETE CASCADE,
    TaskId INT NULL REFERENCES Tasks(TaskId) ON DELETE SET NULL,
    WorkDate DATE NOT NULL,
    HoursWorked DECIMAL(4,2) NOT NULL CHECK (HoursWorked > 0 AND HoursWorked <= 24),
    Description VARCHAR(500) NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', -- DRAFT, SUBMITTED, APPROVED, REJECTED
    ApprovedByMemberId INT NULL REFERENCES ProjectMembers(ProjectMemberId) ON DELETE SET NULL,
    ApprovalDate TIMESTAMPTZ NULL,
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 5. BUSINESS TRIPS & EXPENSES
-- ============================================================================

CREATE TABLE BusinessTrips (
    TripId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProjectId INT NOT NULL REFERENCES Projects(ProjectId) ON DELETE CASCADE,
    TripCode VARCHAR(50) NOT NULL UNIQUE,
    Title VARCHAR(250) NOT NULL,
    Destination VARCHAR(250) NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    AdvanceAmount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    Status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', -- DRAFT, SUBMITTED, APPROVED, REJECTED
    ApprovedByMemberId INT NULL REFERENCES ProjectMembers(ProjectMemberId) ON DELETE SET NULL,
    CreatedByMemberId INT NOT NULL REFERENCES ProjectMembers(ProjectMemberId) ON DELETE RESTRICT,
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BusinessTripMembers (
    TripMemberId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TripId INT NOT NULL REFERENCES BusinessTrips(TripId) ON DELETE CASCADE,
    ProjectMemberId INT NOT NULL REFERENCES ProjectMembers(ProjectMemberId) ON DELETE CASCADE,
    CONSTRAINT UQ_Trip_Member UNIQUE(TripId, ProjectMemberId)
);

CREATE TABLE Expenses (
    ExpenseId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TripId INT NOT NULL REFERENCES BusinessTrips(TripId) ON DELETE CASCADE,
    ClaimantMemberId INT NOT NULL REFERENCES ProjectMembers(ProjectMemberId) ON DELETE CASCADE,
    ExpenseType VARCHAR(50) NOT NULL, -- HOTEL, TRANSPORT, MEALS, OTHER
    AmountPlanned DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    AmountActual DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    ReceiptPath VARCHAR(500) NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', -- DRAFT, SUBMITTED, APPROVED, REJECTED
    ApprovedByMemberId INT NULL REFERENCES ProjectMembers(ProjectMemberId) ON DELETE SET NULL,
    Notes VARCHAR(500) NULL,
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 6. 3-LEVEL APPROVAL WORKFLOWS & SECURE EMAIL TOKENS
-- ============================================================================

CREATE TABLE ApprovalWorkflows (
    WorkflowId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProjectId INT NOT NULL REFERENCES Projects(ProjectId) ON DELETE CASCADE,
    SubmitterMemberId INT NOT NULL REFERENCES ProjectMembers(ProjectMemberId) ON DELETE CASCADE,
    TargetType VARCHAR(50) NOT NULL, -- TIMESHEET, EXPENSE, TRIP, CHANGE_REQUEST, DELIVERABLE
    TargetId INT NOT NULL, -- Reference ID of timesheet, expense, or trip
    CurrentStepNumber INT NOT NULL DEFAULT 1, -- Step 1 (Leader), 2 (PM), 3 (Director)
    WorkflowStatus VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedDate TIMESTAMPTZ NULL
);

CREATE TABLE ApprovalSteps (
    StepId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    WorkflowId INT NOT NULL REFERENCES ApprovalWorkflows(WorkflowId) ON DELETE CASCADE,
    StepNumber INT NOT NULL CHECK (StepNumber IN (1, 2, 3)), -- 1: Leader, 2: PM, 3: Director
    ApproverMemberId INT NOT NULL REFERENCES ProjectMembers(ProjectMemberId) ON DELETE CASCADE,
    StepStatus VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED
    Comments VARCHAR(500) NULL,
    SecureToken VARCHAR(255) NULL, -- Cryptographic signed URL token for quick actions
    TokenExpiry TIMESTAMPTZ NULL,
    ActionDate TIMESTAMPTZ NULL
);

-- ============================================================================
-- 7. ORACLE ERP SPECIALIZED TABLES: RICEFW, INSTANCE & DOCUMENTS
-- ============================================================================

-- RICEFW Registry
CREATE TABLE RicefwRegistry (
    RicefwId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProjectId INT NOT NULL REFERENCES Projects(ProjectId) ON DELETE CASCADE,
    RicefwCode VARCHAR(50) NOT NULL, -- e.g., R01, I03, C10
    RicefwName VARCHAR(250) NOT NULL,
    ModuleCode VARCHAR(20) NOT NULL, -- AP, AR, GL, PO, INV, OM, FA...
    ObjectType VARCHAR(20) NOT NULL, -- REPORT, INTERFACE, CONVERSION, EXTENSION, FORM, WORKFLOW
    Complexity VARCHAR(15) NOT NULL CHECK (Complexity IN ('LOW', 'MEDIUM', 'HIGH')),
    
    -- Document Statuses (Oracle Standard Deliverables)
    FunctionalSpecStatus VARCHAR(30) NOT NULL DEFAULT 'PENDING', -- MD050
    TechnicalSpecStatus VARCHAR(30) NOT NULL DEFAULT 'PENDING',  -- MD070
    
    -- Development & Testing Statuses
    CodingStatus VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
    UnitTestingStatus VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
    SitStatus VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
    UatStatus VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
    
    ResponsibleMemberId INT NULL REFERENCES ProjectMembers(ProjectMemberId) ON DELETE SET NULL,
    SharepointFolderLink VARCHAR(500) NULL,
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedDate TIMESTAMPTZ NULL,
    CONSTRAINT UQ_Project_RicefwCode UNIQUE(ProjectId, RicefwCode)
);

-- Oracle Environment/Instance Tracker
CREATE TABLE OracleInstances (
    InstanceId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProjectId INT NOT NULL REFERENCES Projects(ProjectId) ON DELETE CASCADE,
    InstanceName VARCHAR(50) NOT NULL, -- DEV1, DEV2, TEST1, CRP1, CRP2, UAT, PROD
    OracleVersion VARCHAR(50) NOT NULL,
    InstanceStatus VARCHAR(30) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, REFRESHING, DOWN
    LastRefreshDate DATE NULL,
    Description VARCHAR(500) NULL,
    UpdatedDate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- SharePoint Folders Reference Lookup
CREATE TABLE SharepointMappings (
    MappingId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProjectId INT NOT NULL REFERENCES Projects(ProjectId) ON DELETE CASCADE,
    SharepointSiteUrl VARCHAR(500) NOT NULL,
    RootFolderId VARCHAR(255) NOT NULL,
    RootFolderPath VARCHAR(500) NOT NULL,
    CreatedDate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 8. NATIVE POSTGRESQL ROW-LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

-- Function to check if a user is system admin or belongs to the project
CREATE OR REPLACE FUNCTION check_project_membership(proj_id INT)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN (
        current_setting('app.current_user_role', true) = 'SYSTEM_ADMIN'
        OR EXISTS (
            SELECT 1 
            FROM ProjectMembers pm
            JOIN Users u ON pm.UserId = u.UserId
            WHERE pm.ProjectId = proj_id 
              AND u.Username = current_setting('app.current_username', true)
              AND pm.IsActive = TRUE
        )
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Enable RLS on core tables
ALTER TABLE Projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE ProjectMembers ENABLE ROW LEVEL SECURITY;
ALTER TABLE Tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE Timesheets ENABLE ROW LEVEL SECURITY;
ALTER TABLE BusinessTrips ENABLE ROW LEVEL SECURITY;
ALTER TABLE Expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE RicefwRegistry ENABLE ROW LEVEL SECURITY;

-- Create Policies for RLS
CREATE POLICY project_rls_policy ON Projects 
    FOR ALL USING (check_project_membership(ProjectId));

CREATE POLICY member_rls_policy ON ProjectMembers 
    FOR ALL USING (check_project_membership(ProjectId));

CREATE POLICY task_rls_policy ON Tasks 
    FOR ALL USING (check_project_membership(ProjectId));

CREATE POLICY timesheet_rls_policy ON Timesheets 
    FOR ALL USING (check_project_membership(ProjectId));

CREATE POLICY trip_rls_policy ON BusinessTrips 
    FOR ALL USING (check_project_membership(ProjectId));

CREATE POLICY expense_rls_policy ON Expenses 
    FOR ALL USING (EXISTS (
        SELECT 1 FROM BusinessTrips t WHERE t.TripId = Expenses.TripId AND check_project_membership(t.ProjectId)
    ));

CREATE POLICY ricefw_rls_policy ON RicefwRegistry 
    FOR ALL USING (check_project_membership(ProjectId));
